name: "Pull request"

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: OIDCSession

      - run: aws s3 cp s3://elias-brange-github-oidc-dev-env-bucket/README.md README.md
        shell: bash

  write-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: OIDCSession

      - run: aws s3 cp README.md s3://elias-brange-github-oidc-dev-env-bucket/README.md
        shell: bash

  read-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: OIDCSession

      - run: aws s3 cp s3://elias-brange-github-oidc-prod-env-bucket/README.md README.md
        shell: bash

  write-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: OIDCSession

      - run: aws s3 cp README.md s3://elias-brange-github-oidc-prod-env-bucket/README.md
        shell: bash

  write-prod-with-env:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: OIDCSession

  try-use-pr-role:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.PR_ROLE }}
          role-session-name: OIDCSession
