name: "Workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  read_bucket:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bucket:
          - elias-brange-github-oidc-dev-env-bucket
          - elias-brange-github-oidc-prod-env-bucket
        environment:
          - ""
          - Production
        role_secret:
          - ROLE
          - PR_ROLE
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secretss[matrix.role_secret] }}
          role-session-name: OIDCSession
